/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ryan's PC
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
        setLocationRelativeTo(null);//set the page location 
        setResizable(false);//disable the resizable function
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPos = new javax.swing.JPanel();
        Logo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        ForgotTitle = new javax.swing.JLabel();
        ForgotTitle1 = new javax.swing.JLabel();
        ForgotTitle2 = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPos.setBackground(new java.awt.Color(255, 255, 255));
        pnlPos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryan's PC\\Desktop\\DataStrucAss\\DataStrucAssignment\\DataStructure1\\poseidon system picture\\loading poseidon.png")); // NOI18N
        pnlPos.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlPos.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 150, 20));

        Title.setFont(new java.awt.Font("Open Sans", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 153, 153));
        Title.setText("Poseidon System");
        pnlPos.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        ForgotTitle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ForgotTitle.setText("@2022 Poseidon,All rights reserved.");
        pnlPos.add(ForgotTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 290, -1));

        ForgotTitle1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ForgotTitle1.setText("Description ----------------------------------");
        pnlPos.add(ForgotTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 300, -1));

        ForgotTitle2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ForgotTitle2.setText("System Edition------------------------------");
        pnlPos.add(ForgotTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 290, -1));

        CloseBtn.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        pnlPos.add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        getContentPane().add(pnlPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        MemRecord mr = new MemRecord();
        mr.show();
        dispose();
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited

    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered

    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        ChangePass cp = new ChangePass();
        cp.show();
        dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JLabel ForgotTitle;
    private javax.swing.JLabel ForgotTitle1;
    private javax.swing.JLabel ForgotTitle2;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlPos;
    // End of variables declaration//GEN-END:variables
}
