
import java.io.File;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author zenta
 */
public class MemberEdited extends javax.swing.JFrame {

    /**
     * Creates new form MemberEdited
     */
    public MemberEdited() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    private MemRecord mr;
    private EditMember em;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMemEdited = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblFinish = new javax.swing.JButton();
        lblEditAgain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMemEdited.setBackground(new java.awt.Color(255, 255, 255));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setText("Member record edited");

        btnBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryan's PC\\Desktop\\dataAsssss\\DataStrucAssignment\\DataStructure1\\src\\main\\java\\Icon\\BACK.png")); // NOI18N
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblFinish.setBackground(new java.awt.Color(13, 109, 63));
        lblFinish.setText("Finish");
        lblFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblFinishActionPerformed(evt);
            }
        });

        lblEditAgain.setForeground(java.awt.Color.red);
        lblEditAgain.setText("Edit again");
        lblEditAgain.setBorder(null);
        lblEditAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblEditAgainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMemEditedLayout = new javax.swing.GroupLayout(pnlMemEdited);
        pnlMemEdited.setLayout(pnlMemEditedLayout);
        pnlMemEditedLayout.setHorizontalGroup(
            pnlMemEditedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMemEditedLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlMemEditedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEditAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFinish))
                .addGap(169, 169, 169))
            .addGroup(pnlMemEditedLayout.createSequentialGroup()
                .addGroup(pnlMemEditedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMemEditedLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblHeader))
                    .addGroup(pnlMemEditedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        pnlMemEditedLayout.setVerticalGroup(
            pnlMemEditedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemEditedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(25, 25, 25)
                .addComponent(lblHeader)
                .addGap(36, 36, 36)
                .addComponent(lblFinish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEditAgain, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMemEdited, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMemEdited, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();

        em = new EditMember();
        em.show();
    }//GEN-LAST:event_btnBackActionPerformed

    private void lblFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblFinishActionPerformed
        File myObj = new File("editMember.txt");
        if (myObj.delete()) {
            System.out.println("Deleted the file: " + myObj.getName());
        } else {
            System.out.println("Failed to delete the file.");
        }
        
        dispose();
        mr = new MemRecord();
        mr.show();
    }//GEN-LAST:event_lblFinishActionPerformed

    private void lblEditAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblEditAgainActionPerformed
        dispose();

        em = new EditMember();
        em.show();
    }//GEN-LAST:event_lblEditAgainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberEdited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberEdited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberEdited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberEdited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberEdited().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton lblEditAgain;
    private javax.swing.JButton lblFinish;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JPanel pnlMemEdited;
    // End of variables declaration//GEN-END:variables
}
